domains:
  - name: github
    urls_file: ./urls/github-urls.txt
    enable: true

  - name: apple-corp
    urls_file: ./urls/apple-corp-urls.txt
    enable: false

  - name: gitlab
    urls_file: ./urls/gitlab-urls.txt
    enable: false

  - name: shopify
    urls_file: ./urls/shopify-urls.txt
    enable: false

  - name: shopifycloud
    urls_file: ./urls/shopifycloud-urls.txt
    enable: false

  - name: paypal
    urls_file: ./urls/paypal-urls.txt
    enable: false

  - name: apple
    urls_file: ./urls/test-urls.txt
    enable: false

  - name: shopify
    urls_file: ./urls/test-urls.txt
    enable: false

output_root_path: out
info_log: info.log
package_log: package.log
package_yml: package.yml
